function dx = dyn_zero_to_t_plan(tdummy,in2,udummy)
%DYN_ZERO_TO_T_PLAN
%    DX = DYN_ZERO_TO_T_PLAN(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-Jul-2020 15:19:32

cqi = in2(1,:);
kai = in2(3,:);
kvi = in2(4,:);
sqi = in2(2,:);
t = in2(5,:);
t2 = kai.*t;
t3 = kvi+t2;
dx = [-sqi.*t3;cqi.*t3;0.0;0.0;1.0];
