function dx = dyn_zero_to_t_plan(tdummy,in2,udummy)
%DYN_ZERO_TO_T_PLAN
%    DX = DYN_ZERO_TO_T_PLAN(TDUMMY,IN2,UDUMMY)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    05-Oct-2020 17:10:04

cqi = in2(1,:);
dcqi = in2(3,:);
dsqi = in2(4,:);
kai = in2(5,:);
kvi = in2(6,:);
sqi = in2(2,:);
t = in2(7,:);
t2 = kai.*t;
t3 = kvi+t2;
dx = [-sqi.*t3;cqi.*t3;-dsqi.*t3-kai.*sqi;cqi.*kai+dcqi.*t3;0.0;0.0;1.0];
